### ISSUE TITLE
operon analyzer cleanup

### ISSUE THREAD

**Issue by jimrybarski** [wilkelab/Opfi#124]
- [ ] Correctly identify functions as public or private
- [ ] Add missing code documentation
- [ ] Update README
- [ ] Add examples for custom Filter and Rule
- [ ] Clean imports
- [ ] Make sure symbols aren't being imported through the wrong module

**Comment by clauswilke** [comment]
@jimrybarski Anything to be done here, or can we close this issue also? I would suggest that if there are any specific points that you think could be improved in the future, even if you're not planning to address them right now, file a separate issue for each, with a few sentences providing specifics.

**Comment by jimrybarski** [comment]
This is pretty much done. There are examples of custom rules/filters in the unit tests, we may want to make formal documentation for it eventually.
