### ISSUE TITLE
Documentation for optional dependencies

### ISSUE THREAD

**Issue by afrubin** [wilkelab/Opfi#201]
The documentation at https://opfi.readthedocs.io/en/latest/installation.html#dependencies includes several optional dependencies that might be needed (or required by tests) but does not provide much extra detail. 

For example, when would a user want to use GenericRepeatFinder? From what I could tell it is only mentioned on the installation page and is not cited in the paper.

Can the developers provide additional guidance in the documentation as to when someone would want to use Diamond or MMseqs2 instead of BLAST+?

**Comment by Thomieh73** [comment]
Just a comment on GenericRepeatFinder, it has a bioconda package: https://anaconda.org/bioconda/genericrepeatfinder
you can add that to the Readthedocs installation instructions
